project:
  type: website
  output-dir: docs  # docs directory of master branch

website:
  title: "LLM dialogues"
  cookie-consent: false
  
  search: false
  
  navbar:
    pinned: true
    
    search: false
    
    right:
      - href: index.qmd
        text: Home
      - href: posts.qmd
        text: Blog        

        
  page-footer: 
    center: "© 2025. This Website is made with [Quarto](https://quarto.org/)."
    background: light



format:
  html: default

    
brand:
  light: _brand.yml
  dark: _brand-dark.yml
  
filters:
  - highlight-text
  - lightbox
lightbox: 
  match: auto
  effect: zoom
  desc-position: bottom
  loop: true
